s1 = int(input("pick a number"))
s2 = int(input("pick a number"))
s3 = int(input("pick a number"))
s4 = int(input("pick a number"))
s5 = int(input("pick a number"))
s6 = int(input("pick a number"))
s7 = int(input("pick a number"))
s8 = int(input("pick a number"))
tple = (s1,s2,s3,s4,s5,s6,s7,s8)
print(tple)